### ISSUE TITLE
Sync Across Devices?

### ISSUE THREAD

**Issue by sebthom** [justine-george/tab-keeper-react-chrome-extension#97]
Thanks for this promising extension!

Is there a documentation on how to enable sync across devices? I didn't find any and also did not see any configuration options (e.g. sharable keys, etc.) to link to devices to the same storage.

My use case: I am trying to sync tabs between Chrome on my desktop and Kiwi Browser (chrome based) on Android

**Comment by justine-george** [comment]
I appreciate that you like the extension!

Unfortunately, the ability to sync between different devices, especially from Chrome on desktop to Kiwi Browser on Android, is limited by certain restrictions. The cross-device synchronization feature relies on a unique token that is synced across devices automatically. If Google Sync is enabled on your Chrome browser, this feature is turned on automatically, facilitating a seamless sync experience where supported. You can learn more about this process [here](https://www.jgeorge.dev/posts/how-anonymous-login-works-on-tabkeeper). However, due to Google's policies, Chrome's sync capabilities are limited strictly to the original Google Chrome browser, leaving Chromium-based browsers such as Kiwi Browser without this sync functionality.

For further information, you can refer to a discussion on this issue in the Kiwi Browser repo [here](https://github.com/kiwibrowser/src.next/issues/694#issue-1352149309).

While I understand this might not be the ideal solution for your use case, I hope this clarifies the limitations and provides some context.

**Comment by sebthom** [comment]
Thanks for your prompt and detailed response! Maybe you could add a note about this Google imposed limitation (Sync only across Google Chrome browsers) somewhere close to where you list the sync feature.

**Comment by justine-george** [comment]
That's a great suggestion, thank you! Meanwhile I'm closing this issue as not planned.

**Comment by justine-george** [comment]
Hi @sebthom, I noticed the [issue](https://github.com/kiwibrowser/src.next/issues/1087) you raised in the Kiwi Browser repository. To assist with transferring all your open tabs to a new device, I recommend a workaround using Tab Keeper's export/import app data feature. Here’s how you can do it:

1. Save the current session in Tab Keeper on your old phone.
2. Click on the Settings cog icon > Data Management > Export App Data to File.
3. On your new phone, navigate to the same settings to Import the app data file.
4. Load the backup file to import the saved session.
5. Return to the main page and restore the session.

I hope this resolves your issue.
